<?php

namespace App\Actions;

use App\Models\Membership;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;

class RenewMembership
{
    /**
     * Renew an active or expired membership by creating a NEW membership
     * record (SPEC-004 FR-005, BR-011; AM-08).
     *
     * The new record keeps the source membership's client and plan, starts on
     * the given start date (defaults to the day after the source's end date),
     * uses the given duration in days (defaults to the source's duration), and
     * is created with status `pending` (BR-005) with its end date computed by
     * the model's creating hook (BR-003). The source record is never modified
     * (BR-011). The new membership's cuota is auto-generated by the model's
     * `created` hook (SPEC-005 FR-001, ADR-005); no Payment is created.
     *
     * @param  string|null  $startDate  new start date (YYYY-MM-DD); defaults to end_date + 1 day
     * @param  int|null  $durationDays  new duration in days; defaults to the source duration
     *
     * @throws AuthorizationException when the user is not ADMIN
     * @throws ValidationException when the source is pending/cancelled (ERR-005),
     *                             the plan is inactive (ERR-001) or the new period is invalid (ERR-003)
     */
    public function handle(Membership $membership, ?string $startDate = null, ?int $durationDays = null): Membership
    {
        $this->authorize();

        $startDate ??= $membership->end_date->copy()->addDay()->toDateString();
        $durationDays ??= $membership->duration_days;

        $this->validate($membership, $startDate, $durationDays);

        return DB::transaction(function () use ($membership, $startDate, $durationDays): Membership {
            return Membership::create([
                'client_id' => $membership->client_id,
                'plan_id' => $membership->plan_id,
                'start_date' => $startDate,
                'duration_days' => $durationDays,
            ]);
        });
    }

    /**
     * Server-side enforcement (SPEC-004 §9; AGENTS.md §17): renewal creates a
     * NEW membership record, so the `create` ability authorizes it (BR-015).
     * The Filament action visibility already restricts the UI to ADMIN; this
     * check is defense in depth so the Action stays safe outside the UI.
     */
    protected function authorize(): void
    {
        Gate::authorize('create', Membership::class);
    }

    /**
     * Validate renewal input (SPEC-004 ERR-005, ERR-001, ERR-003; AM-08).
     */
    protected function validate(Membership $membership, ?string $startDate, ?int $durationDays): void
    {
        if (! in_array($membership->status, [Membership::STATUS_ACTIVE, Membership::STATUS_EXPIRED], true)) {
            throw ValidationException::withMessages([
                'membership' => 'Only active or expired memberships can be renewed.',
            ]);
        }

        Validator::make([
            'start_date' => $startDate,
            'duration_days' => $durationDays,
        ], [
            'start_date' => ['required', 'date'],
            'duration_days' => ['required', 'integer', 'min:1'],
        ])->validate();

        if (! $membership->plan->is_active) {
            throw ValidationException::withMessages([
                'plan' => 'The membership cannot be renewed against an inactive plan.',
            ]);
        }
    }
}
