<?php

namespace App\Policies;

use App\Models\Cuota;
use App\Models\Role;
use App\Models\User;

class CuotaPolicy
{
    /**
     * ADMIN and TRAINER may list / search cuotas (SPEC-005 BR-011, PY-01;
     * FR-003).
     */
    public function viewAny(User $user): bool
    {
        return $user->hasAnyRole([Role::ADMIN, Role::TRAINER]);
    }

    /**
     * ADMIN and TRAINER may view a cuota's detail and payment history
     * (SPEC-005 BR-011, FR-003). A CLIENT may view only their OWN cuota,
     * reached through its membership (SPEC-013 BR-002, C-13; ADR-007).
     */
    public function view(User $user, Cuota $cuota): bool
    {
        return $user->hasAnyRole([Role::ADMIN, Role::TRAINER])
            || ($user->hasRole(Role::CLIENT) && $cuota->membership?->client_id === $user->clientId());
    }

    /**
     * ADMIN and TRAINER may update a cuota — the only update is the
     * pending-amount edit (FR-002, D-02 option 2, BR-012). The pending-only
     * rule is enforced by Cuota::updateAmount(), not here (ERR-007).
     */
    public function update(User $user, Cuota $cuota): bool
    {
        return $user->hasAnyRole([Role::ADMIN, Role::TRAINER]);
    }

    /**
     * No create policy is registered on purpose: cuotas are never created
     * manually — they are auto-generated by the Membership `created` hook
     * (FR-001, ADR-005).
     *
     * No delete policy is registered on purpose: cuotas are never hard-deleted
     * in the MVP (BR-009); no delete operation is provided.
     */
}
